# Generated by Django 3.1.3 on 2020-11-21 19:19

from django.db import migrations, models
import django.utils.timezone
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimage',
            name='file',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
