# Generated by Django 3.1.3 on 2020-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_enable_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='fb_user_id',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
