# Generated by Django 3.1.3 on 2020-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
