# Generated by Django 3.1.4 on 2021-01-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0007_test_additional_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='fb_user_id',
        ),
        migrations.AddField(
            model_name='test',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
