# Generated by Django 3.1.4 on 2021-01-09 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='creation_ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='fb_id',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Facebook ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(default='0.0.0.0', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
